name: Hexo Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Hexo
        run: npm install hexo-cli -g && npm install

      # 云端自动拉取Next主题，不用本地上传themes文件夹
      - name: Clone Next Theme
        run: git clone https://github.com/next-theme/hexo-theme-next.git themes/next

      - name: Generate static pages
        run: hexo clean && hexo g

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
